### PR TITLE
Fix vat

### PR DESCRIPTION
**Pull request by softmonkeyjapan**

### CODE REVIEW

**Comment by Klyper** [comment]
Hi,

Thanks again for the update.
I downloaded the complete plugin and uploaded it again but their is an error.
I added the file below.
https://dl.dropboxusercontent.com/u/858887/error_opencart-excel-export2.txt

**Comment by softmonkeyjapan** [comment]
mmm...this is weird that your opencart installation actually cannot find data that has suppose to be there. I'll make a fix again but this is definitely weird. I've tried the new code on a live production site as well as on a fresh Opencart install and it works.

**Comment by Klyper** [comment]
Did i download the right version?
I downloaded the zip version from the main site (
https://github.com/softmonkeyjapan/opencart-excel-export)

2014-09-14 13:40 GMT+02:00 Loïc KARTONO notifications@github.com:

**Comment by softmonkeyjapan** [comment]
You actually uploaded the right version. I made a fix which will also handle data that does not exists yet, so no crash anymore but just empty values. Try it and let me know.
Download the plugin from the main site as you did previously

**Comment by Klyper** [comment]
Now it works :)
Thank you very much!

2014-09-14 13:53 GMT+02:00 Loïc KARTONO notifications@github.com:

**Pull request merged**
